spring.application.name=erp
server.port=8081

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Default user credentials
#spring.security.user.name=admin@gmail.com
#spring.security.user.password=123456

# MySQL database connection details
spring.datasource.url=jdbc:mysql://localhost:3306/textipro
spring.datasource.username=root
spring.datasource.password=root

# Additional options (optional)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate=DEBUG

#Jasper is Tomcat's JSP engine
logging.level.org.apache.jasper=DEBUG   
logging.level.org.springframework.web.servlet=DEBUG

# Log output will go to app.log in your project's root
logging.file.name=app.log 
# Enables DEBUG level for web components 
logging.level.org.springframework.web=DEBUG  
logging.level.org.springframework.web.servlet=TRACE


javax.el.ExpressionFactory=com.sun.el.ExpressionFactoryImpl
spring.thymeleaf.enabled=false




